# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

commands:
  print_pipeline_id:
    parameters:
      sample_name:
        type: string
        default: "Sample Name"
    steps:
      - run:
          name: "Print Pipeline ID"
          command: echo $CIRCLE_WORKFLOW_ID
      - run:
          name: "Print Sample Name"
          command: echo "Sample Name - << parameters.sample_name >>"

jobs:
  # Define a job called "print hello world"
  print_hello_wold:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Hello World"
          command: echo "Hello World"
      - run: |
          mkdir -p /tmp/test
          echo "Hello World" > /tmp/test/hello.txt
          cat /tmp/test/hello.txt

      - persist_to_workspace:
          root: /tmp/test
          paths:
            - hello.txt

  # Define a job called "print project creator name"
  print_project_creator:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Print Project Creator"
          command: echo $PROJECT_CREATOR
      - attach_workspace:
          at: /tmp/test
      - run: |
          cat /tmp/test/hello.txt
      - print_pipeline_id:
          sample_name: "Another name"

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello_wold
      - print_project_creator:
          requires:
            - print_hello_wold
